spring:
  elasticsearch:
    rest:
      uris: ${buaa.elasticsearch.uris}
      username: ${buaa.elasticsearch.username}
      password: ${buaa.elasticsearch.password}

buaa:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: com.central.search.controller