spring:
  datasource:
    url: jdbc:mysql://${buaa.datasource.ip}:3306/file_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${buaa.datasource.username}
    password: ${buaa.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.file.model
  global-config:
    db-config:
      id-type: INPUT

buaa:
  file-server:
    type: s3
    #fdfs:
    #  web-url: ${buaa.fdfs.web-url}
    s3:
      access-key: ${buaa.s3.access-key}
      accessKeySecret: ${buaa.s3.accessKeySecret}
      endpoint: ${buaa.s3.endpoint}
      bucketName: ${buaa.s3.bucketName}
  swagger:
    enabled: true
    title: 文件中心
    description: 文件中心接口文档
    version: 1.0
    base-package: com.central.file.controller
  #多租户配置
  tenant:
    enable: true

#fastDFS配置
#fdfs:
#  soTimeout: 1500
#  connectTimeout: 600
#  trackerList: ${buaa.fdfs.trackerList}